---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backflow.io
  resources:
  - backflowpolicies
  - driftproposals
  - scmconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backflow.io
  resources:
  - backflowpolicies/finalizers
  - driftproposals/finalizers
  - scmconnections/finalizers
  verbs:
  - update
- apiGroups:
  - backflow.io
  resources:
  - backflowpolicies/status
  - driftproposals/status
  - scmconnections/status
  verbs:
  - get
  - patch
  - update
